version: '3.4'

networks:
  dev:
   driver: bridge

services:
  videotek-mvc:
   image: docker.io/videotek/videotek-mvc 
   container_name: videotek-mvc
   ports:
     - 8081:7000
   volumes:
     - ./Video.Web/appsettings.json:/app/appsettings.json
  videotek-sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: videotek-sql
    ports: # not actually needed, because the two services are on the same network.
      - 1433:1433 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password